env:
  global:
    - SWIFT_SNAPSHOT=swift-4.2-RELEASE
    - SONARCLOUD_ELIGIBLE=true

matrix:
  include:
    - os: osx
      osx_image: xcode10
      sudo: required

before_install:
  - git clone -b add-sonarcloud https://github.com/ladislas/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
